### ISSUE TITLE
Add month

### ISSUE THREAD

**Issue by va3093** [de-vri-es/gregorian-rs#1]
I am interested in adding a `add_months` function. Does that sound like a reasonable thing to have in this library.

**Comment by de-vri-es** [comment]
It would be, but I ran into some trouble trying to decide what it should do if the specific day doesn't exist in the new month.

For example, if you add one month to January 31, what should the result be? I think it depends on the application whether February 28 (or 29 in leap years) or March 1 is what you want.

I suppose we could also return an `Result<Date, InvalidDayOfMonth>`. That also has the nicety that for all valid values, adding and subtracting the same amount of months is guaranteed to return the original date.

We could even have three versions: one that returns a Result, one that rounds down and one that rounds up.

**Comment by va3093** [comment]
yeah. I think returning an error to cover those edge cases is the right thing to do. Then the users can decide how they want to handle those cases.

**Comment by de-vri-es** [comment]
Right, implemented most of it on master now.

I also added `InvalidDayOfMonth::next_valid()` and `InvalidDayOfMonth::prev_valid()` to help deal with the edge cases.
That allows you to write `date.add_months(15).unwrap_or_else(|e| e.next_valid())`.

I think I still want to add an extension trait to allow `Result<Date, InvalidDayOfMonth>::or_next_valid()` and `or_prev_valid()`.
Then you can just write `date.add_months(15).or_next_valid()`.

I also probably want to add more tests in general before the next release.

**Comment by de-vri-es** [comment]
This has been released as 0.2.0 :)
