### ISSUE TITLE
Calculations between dates.

### ISSUE THREAD

**Issue by wildwestrom** [de-vri-es/gregorian-rs#2]
I'm writing a program that does math with dates. 
It would be useful to have some kind of method that can take two dates and return a duration in units.
Something like [this method](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/temporal/TemporalUnit.html#between(java.time.temporal.Temporal,java.time.temporal.Temporal)).

Would you be willing to accept pull requests for such a feature?

**Comment by de-vri-es** [comment]
Hey, thanks for opening an issue!

I do think this is useful. Note that you can do this now with [`Date::days_since_year_zero()`](https://docs.rs/gregorian/latest/gregorian/struct.Date.html#method.days_since_year_zero), but it doesn't look super pretty: `date1.days_since_year_zero() - date2.days_since_year_zero()`.

I think the real challenge here is to come up with a nice interface. For example, do we want a delta type for `Days`, `Months`, and `Years` that you can just add to a `Date`? Or is it sufficient to just have `Date::days_since(self, other: Date) -> i32/i64`?

And if we want `months_since()` and/or `years_since()` how would we round?

I'm open to suggestions and PRs. If you're going to make a big API addition it might be good to discuss it first though.

**Comment by wildwestrom** [comment]
Unfortunately I am not an expert in API design, so I can't say for sure what would be best.
Maybe we can use this issue as discussion first. I'll give you my particular use case. I'd like to create a calendar that shows how long you have left to live, a bit like this [waitbutwhy.com article](https://waitbutwhy.com/2014/05/life-weeks.html). So in order to do this I need a function that takes in two parameters: A birthday, this can be an instance of a `Date` struct. Then a lifespan, which can either be an integer or a type of time period. This function will return some data; The total lifespan, how long they've already been alive with respect to a date (usually the present), and how much life is remaining. I think it's also important to have the function be generic enough to be able to specify particular units of time, like weeks, months, years, etc.
I've already implemented such a model in Clojure, as I'm most comfortable in this language.
```clojure
(ns wildwestrom.death-calendar.model
  (:import (java.time LocalDate)
           (java.time.temporal TemporalAmount ChronoUnit))
  (:gen-class))

(set! *warn-on-reflection* true)

(defn death-day
  [^LocalDate birth-day ^TemporalAmount life-span]
  (.plus birth-day life-span))

(defn total-days
  [^LocalDate birth-day ^TemporalAmount life-span ^ChronoUnit unit]
  (.between unit
            birth-day
            (death-day birth-day life-span)))

(defn lived-days
  [^LocalDate birth-day ^TemporalAmount life-span ^ChronoUnit unit]
  (let [calculated (.between unit
                             (LocalDate/now)
                             (death-day birth-day life-span))]
    calculated))

(defn calendar-data
  [^LocalDate birth-day
   ^TemporalAmount life-span
   & {:keys [unit]
      :or {unit ChronoUnit/DAYS}}]
  (let [total-life (total-days birth-day life-span unit)
        remaining  (lived-days birth-day life-span unit)
        lived      (- total-life remaining)
        cal-map    {:total     total-life
                    :lived     lived
                    :remaining remaining}]
    (if (> 0 remaining)
      (assoc cal-map :dead? true)
      cal-map)))
```
These functions rely on the interplay of the classes `LocalDate`, `TemporalAmount`, and `ChronoUnit`. I'm not sure how the Rust API should look, but perhaps it could simply mimic the Java APIs by having Date, Period, and Unit, structs of some sort. As for how to handle edge cases, I wouldn't be surprised if this problem has mostly been solved by other libraries.

In Rust, I've only gotten as far as implementing the first function:
```rust
use gregorian::Date;

fn death_day(birthday: Date, lifespan: i16) -> Date {
    return match birthday.add_years(lifespan) {
        Ok(date) => date,
        Err(wrongdate) => wrongdate.prev_valid(),
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn given_birthday_and_lifespan_return_death_day() {
        assert_eq!(
            Date::new(2080, 1, 1).unwrap(),
            death_day(Date::new(2000, 1, 1).unwrap(), 80)
        );
        assert_eq!(
            Date::new(2095, 2, 28).unwrap(),
            death_day(Date::new(1996, 2, 29).unwrap(), 99)
        );
        assert_eq!(
            Date::new(2998, 8, 15).unwrap(),
            death_day(Date::new(1998, 8, 15).unwrap(), 1000)
        );
    }
}
```

**Comment by wildwestrom** [comment]
@de-vri-es Just a starting point.
```rust
impl Date {
//...
	/// Compute the difference in days between two dates.
	///
	/// This does not include the end date.
	/// For example, difference between the same date will be 0.
	pub const fn diff_days(date_1: Date, date_2: Date) -> i32 {
		return date_2.days_since_year_zero() - date_1.days_since_year_zero()
	}
///...
}
```

**Comment by de-vri-es** [comment]
We could certainly start with something like that. I would prefer to call it `days_since()` though, to keep in line with the naming of `Instant::duration_since()`. But unlike `duration_since()` I do believe we should return a signed type like you suggest, so we can do `past_date.days_since(future_date)` and get a negative number.

The only thing I'm still contemplating is if it should return a simple `i32` or wrap it in something like `Days(i32)` for more convenient type safety.

**Comment by wildwestrom** [comment]
Ok, no problem with the naming convention. Here's a rudimentary implementation of `months_since`. Haven't figured out how to keep it a `const fn`.
```rust
	pub fn months_since(date_1: Date, date_2: Date) -> i32 {
		let mut months = 0;
		fn round_month(m: i32, f: &dyn Fn(i32) -> Result<Date, InvalidDayOfMonth>) -> Date {
			match f(m) {
				Ok(month) => month,
				Err(e) => e.next_valid(),
			}
		}
		if Self::days_since(date_1, date_2) > 0 {
			while round_month(months, &|m| Date::add_months(date_1, m)) < date_2 {
				months += 1;
			}
		} else if Self::days_since(date_1, date_2) < 0 {
			while round_month(months, &|m| Date::sub_months(date_1, m)) < date_2 {
				months -= 1;
			}
		}
		return months;
	}
```

**Comment by de-vri-es** [comment]
I'm not entirely sure what we want `months_since` to do about rounding. Does rounding down always make sense? 

I also don't think we want a loop to implement this. It will be quite inefficient when the date difference is very large.

However, we could simply start with `days_since()` and see about the rest later. Do you want to make a PR for it? "No" is a valid answer too ;)

**Comment by wildwestrom** [comment]
I'd be happy to start a PR.
Here it is #3.
