### ISSUE TITLE
cannot find function `localtime_r` in crate `libc`

### ISSUE THREAD

**Issue by cstkingkey** [de-vri-es/gregorian-rs#4]

**Comment by de-vri-es** [comment]
Thank you for reporting the issue.

Could you include the full error and tell us which platform you got this error on?

**Comment by cstkingkey** [comment]
under windows msvc.

``
if libc::localtime_r(&time, &mut tm).is_null() {
    |                      ^^^^^^^^^^^ help: a function with a similar name exists: `localtime_s`
``

**Comment by de-vri-es** [comment]
Sorry for the long delay. I've fixed the issue and released it as 0.2.2.

Thanks again for reporting this!
